spring.application.name=demo
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
resend.api.key=${RESEND_API_KEY:}
resend.from.address=onboarding@resend.dev
otel.java.global-autoconfigure.enabled=true
supabase.url=${SUPABASE_URL:}
supabase.apiKey=${SUPABASE_API_KEY:}
supabase.bucket=${SUPABASE_BUCKET:}
firebase.credentialFilePath=${FIREBASE_CREDENTIAL_FILE_PATH:}
firebase.dataBaseUrl=${FIREBASE_DATABASE_URL:}
server.port=8448
