spring.application.name=demo

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.mail.host=smtp.gmail.com
spring.mail.port=465
resend.api.key=${RESEND_API_KEY:}
resend.from.address=onboarding@resend.dev
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.socketFactory.port=465
spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory
spring.mail.properties.mail.smtp.socketFactory.fallback=false


otel.java.global-autoconfigure.enabled=true

supabase.url=${SUPABASE_URL:}
supabase.apiKey=${SUPABASE_API_KEY:}
supabase.bucket=${SUPABASE_BUCKET:}
firebase.credentialFilePath=${FIREBASE_CREDENTIAL_FILE_PATH:}
firebase.dataBaseUrl=${FIREBASE_DATABASE_URL:}
server.port=8448
